// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: x_error_code.proto

package error_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_SUCCESS          ErrorCode = 0
	ErrorCode_PARAM_ERROR      ErrorCode = 10000001 //参数错误
	ErrorCode_PERMISSION_ERROR ErrorCode = 10000002 //权限拒绝
	ErrorCode_NOT_FOUND_ERROR  ErrorCode = 10000003 //
	ErrorCode_INTERNAL_ERROR   ErrorCode = 10000004 //服务错误
	ErrorCode_NOT_LOGIN_ERROR  ErrorCode = 1000005
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:        "SUCCESS",
		10000001: "PARAM_ERROR",
		10000002: "PERMISSION_ERROR",
		10000003: "NOT_FOUND_ERROR",
		10000004: "INTERNAL_ERROR",
		1000005:  "NOT_LOGIN_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"SUCCESS":          0,
		"PARAM_ERROR":      10000001,
		"PERMISSION_ERROR": 10000002,
		"NOT_FOUND_ERROR":  10000003,
		"INTERNAL_ERROR":   10000004,
		"NOT_LOGIN_ERROR":  1000005,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_x_error_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_x_error_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ErrorCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ErrorCode(num)
	return nil
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_x_error_code_proto_rawDescGZIP(), []int{0}
}

var File_x_error_code_proto protoreflect.FileDescriptor

var file_x_error_code_proto_rawDesc = []byte{
	0x0a, 0x12, 0x78, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x78, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x2a, 0x8b, 0x01, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0b, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x81, 0xad, 0xe2,
	0x04, 0x12, 0x17, 0x0a, 0x10, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x82, 0xad, 0xe2, 0x04, 0x12, 0x16, 0x0a, 0x0f, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x83, 0xad,
	0xe2, 0x04, 0x12, 0x15, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x84, 0xad, 0xe2, 0x04, 0x12, 0x15, 0x0a, 0x0f, 0x4e, 0x4f, 0x54,
	0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xc5, 0x84, 0x3d,
	0x42, 0x17, 0x5a, 0x15, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x69, 0x64, 0x6c, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
}

var (
	file_x_error_code_proto_rawDescOnce sync.Once
	file_x_error_code_proto_rawDescData = file_x_error_code_proto_rawDesc
)

func file_x_error_code_proto_rawDescGZIP() []byte {
	file_x_error_code_proto_rawDescOnce.Do(func() {
		file_x_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_x_error_code_proto_rawDescData)
	})
	return file_x_error_code_proto_rawDescData
}

var file_x_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_x_error_code_proto_goTypes = []interface{}{
	(ErrorCode)(0), // 0: x_error_code.ErrorCode
}
var file_x_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_x_error_code_proto_init() }
func file_x_error_code_proto_init() {
	if File_x_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_x_error_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_x_error_code_proto_goTypes,
		DependencyIndexes: file_x_error_code_proto_depIdxs,
		EnumInfos:         file_x_error_code_proto_enumTypes,
	}.Build()
	File_x_error_code_proto = out.File
	file_x_error_code_proto_rawDesc = nil
	file_x_error_code_proto_goTypes = nil
	file_x_error_code_proto_depIdxs = nil
}
